---
- name: Restart wg0
  systemd:
    name: wg-quick@wg0.service
    state: restarted
    enabled: yes
    daemon_reload: yes
  become: true
  become_user: root

- name: Apply sysctl
  command: sysctl -p
  become: true
  become_user: root

- name: Restart nftables
  systemd:
    name: nftables
    state: restarted
    enabled: yes
    daemon_reload: yes
  become: true
  become_user: root

- name: Restart avahi
  systemd:
    name: avahi-daemon
    state: restarted
    enabled: yes
    daemon_reload: yes
  become: true
  become_user: root
